// adding some basic pastes into ui
document.getElementById("str").innerHTML = Str;
document.getElementById("agi").innerHTML = Agi;
document.getElementById("stam").innerHTML = Stam;
document.getElementById("int").innerHTML = Int;
document.getElementById("spi").innerHTML = Spi;
document.getElementById("rap").innerHTML = BaseRAP;
let rangehit = Math.round(RangeHitChance * 100) / 100;
document.getElementById("rangehit").innerHTML = rangehit + " %";
let rangecrit = Math.round(RangeCritChance * 100) / 100;
document.getElementById("rangecrit").innerHTML = rangecrit + " %";
document.getElementById("haste").innerHTML = HasteRating;
document.getElementById("arp").innerHTML = ArmorPen;
document.getElementById("map").innerHTML = BaseMAP;
let meleehit = Math.round(MeleeHitChance * 100) / 100;
document.getElementById("meleehit").innerHTML = meleehit + " %";
let meleecrit = Math.round(MeleeCritChance * 100) / 100;
document.getElementById("meleecrit").innerHTML = meleecrit + " %";
document.getElementById("exp").innerHTML = Expertise + "1";
